<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Helper;

use Magento\Store\Model\Store;
use FjodorMaller\Base\Helper\Base;

/**
 * Class Data
 */
class Data extends Base
{
    const XML_PATH_MODULE_GENERAL_ENABLED        = 'fjodormaller_distribution/general/enabled';

    const XML_PATH_MODULE_GENERAL_DEAD_INTERVAL  = 'fjodormaller_distribution/general/dead_interval';

    const XML_PATH_MODULE_CRON_ENABLED           = 'fjodormaller_distribution/cron/enabled';

    const XML_PATH_MODULE_CRON_CHECK_ACTIVE_ONLY = 'fjodormaller_distribution/cron/check_active_only';

    const XML_PATH_MODULE_LOGGING_ENABLED        = 'fjodormaller_logging/fjodormaller_distribution/enabled';

    const XML_PATH_MODULE_LOGGING_LOCATION       = 'fjodormaller_logging/fjodormaller_distribution/location';

    const XML_PATH_MODULE_LOGGING_FILENAME       = 'fjodormaller_logging/fjodormaller_distribution/filename';

    /**
     * Return true if cron job is enabled.
     *
     * @param null|string|bool|int|Store $store
     *
     * @return bool
     */
    public function isCronEnabled($store = null)
    {
        return $this->isFlag(self::XML_PATH_MODULE_CRON_ENABLED, $store);
    }

    /**
     * Returns true if flag for check active only is enabled.
     *
     * @param null|string|bool|int|Store $store
     *
     * @return bool
     */
    public function isCheckActiveOnly($store = null)
    {
        return $this->isFlag(self::XML_PATH_MODULE_CRON_CHECK_ACTIVE_ONLY, $store);
    }

    /**
     * Returns the timeout interval for distributions to be dead.
     *
     * @param null|string|bool|int|Store $store
     *
     * @return int
     */
    public function getDeadInterval($store = null)
    {
        return (int)$this->getValue(self::XML_PATH_MODULE_GENERAL_DEAD_INTERVAL, $store);
    }
}
