<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Ui\DataProvider\Distribution\Form\Modifier;

use FjodorMaller\Distribution\Api\Data\DistributionInterface;
use Magento\Framework\Registry;
use Magento\Framework\Stdlib\ArrayManager;
use Magento\Ui\DataProvider\Modifier\ModifierInterface;

/**
 * Class General
 */
class General implements ModifierInterface
{
    /**
     * @var Registry
     */
    protected $_registry;

    /**
     * @var ArrayManager
     */
    protected $_arrayManager;

    /**
     * @param Registry     $registry
     * @param ArrayManager $arrayManager
     */
    public function __construct(
        Registry $registry,
        ArrayManager $arrayManager
    ) {
        $this->_registry     = $registry;
        $this->_arrayManager = $arrayManager;
    }

    /**
     * @inheritdoc
     */
    public function modifyData(array $data)
    {
        $model = $this->_registry->registry('current_distribution');
        if ($model && $model->getId()) {
            $data[ $model->getId() ][ DistributionInterface::PARAM_NAME ] = $model->getData();
        }

        return $data;
    }

    /**
     * @inheritdoc
     */
    public function modifyMeta(array $meta)
    {
        return $meta;
    }
}
