<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Ui\Component\Form\Distribution\Adapter\AwsS3\Region;

use Magento\Framework\Data\OptionSourceInterface;

/**
 * Class Options
 */
class Options implements OptionSourceInterface
{
    /**
     * @var array
     */
    protected $_options;

    /**
     * Returns the options as array.
     *
     * @return array
     */
    public function toArray()
    {
        return [
            'us-east-2'      => 'USA Ost (Ohio)',
            'us-east-1'      => 'USA Ost (Nord-Virginia)',
            'us-west-1'      => 'USA West (Nordkalifornien)',
            'us-west-2'      => 'USA West (Oregon)',
            'ap-south-1'     => 'Asien-Pazifik (Mumbai)',
            'ap-northeast-2' => 'Asien-Pazifik (Seoul)',
            //'ap-northeast-3' => 'Asien-Pazifik (Osaka-Lokal)',
            'ap-southeast-1' => 'Asien-Pazifik (Singapur)',
            'ap-southeast-2' => 'Asien-Pazifik (Sydney)',
            'ap-northeast-1' => 'Asien-Pazifik (Tokio)',
            'ca-central-1'   => 'Kanada (Zentral)',
            'cn-north-1'     => 'China (Peking)',
            'cn-northwest-1' => 'China (Ningxia)',
            'eu-central-1'   => 'EU (Frankfurt)',
            'eu-west-1'      => 'EU (Irland)',
            'eu-west-2'      => 'EU (London)',
            'eu-west-3'      => 'EU (Paris)',
            'sa-east-1'      => 'Südamerika (São Paulo)',
        ];
    }

    /**
     * @inheritdoc
     */
    public function toOptionArray()
    {
        if (!$this->_options) {
            $this->_options = [];
            foreach ($this->toArray() as $value => $label) {
                $this->_options[] = [
                    'value' => $value,
                    'label' => $label,
                ];
            }
        }

        return $this->_options;
    }
}
