<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Controller\Adminhtml\Index;

use FjodorMaller\Distribution\Api\Data\DistributionInterface;
use Magento\Framework\Controller\Result\Json;
use Magento\Framework\Controller\ResultFactory;
use Magento\Framework\DataObject;

/**
 * Class Check
 */
class Check extends Base
{
    /**
     * @inheritdoc
     */
    public function execute()
    {
        $response = new DataObject();
        $response->setError(true);
        $data = $this->getRequest()->getParams();
        $data = $this->_dataProcessor->filter($data);
        $adapter = $data[ DistributionInterface::ADAPTER ] ?? null;
        if ($adapter && isset($data[ 'options' ][ $adapter ])) {
            $isValid = $this->_distributionService->isValidAdapter(
                $adapter,
                $data[ 'options' ][ $adapter ]
            );
            $response->setError(!$isValid);
            $response->setMessage(
                $isValid ? __('Adapter settings are valid') : __('Adapter settings are invalid')
            );
        }
        /* @var $resultJson Json */
        $resultJson = $this->resultFactory->create(ResultFactory::TYPE_JSON);

        return $resultJson->setData($response);
    }
}
