<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Controller\Adminhtml\Index;

use FjodorMaller\Distribution\Api\Data\DistributionInterface;
use Magento\Backend\Model\View\Result\Page;

/**
 * Class Edit
 */
class Edit extends Base
{
    /**
     * @inheritdoc
     */
    public function execute()
    {
        $id    = (int)$this->getRequest()->getParam(DistributionInterface::DISTRIBUTION_ID);
        $model = $this->_factory->create();
        if ($id) {
            $model->load($id);
            if (!$model->getId()) {
                $this->messageManager->addErrorMessage(__('This distribution no longer exists.'));

                return $this->resultRedirectFactory->create()->setPath('*/*/');
            }
        }
        $this->_coreRegistry->register('current_distribution', $model);
        /* @var $resultPage Page */
        $resultPage = $this->_initAction();
        $resultPage->addBreadcrumb(
            $id ? __('Edit Distribution') : __('New Distribution'),
            $id ? __('Edit Distribution') : __('New Distribution')
        );
        $resultPage->getConfig()->getTitle()->prepend(__('Distributions'));
        $resultPage->getConfig()->getTitle()->prepend(
            $model->getId() ? sprintf('Edit Distribution: "%s"', $model->getName()) : __('New Distribution')
        );

        return $resultPage;
    }
}
