<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Controller\Adminhtml\Index;

/**
 * Class Grid
 */
class Grid extends Base
{
    /**
     * @inheritdoc
     */
    public function execute()
    {
        return $this->_resultLayoutFactory->create();
    }
}
