<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Controller\Adminhtml\Index;

use Magento\Backend\Model\View\Result\Page;

/**
 * Class Index
 */
class Index extends Base
{
    /**
     * @inheritdoc
     */
    public function execute()
    {
        if ($this->getRequest()->getQuery('ajax')) {
            $resultForward = $this->_resultForwardFactory->create();
            $resultForward->forward('grid');

            return $resultForward;
        }
        /* @var $resultPage Page */
        $resultPage = $this->_initAction();
        $resultPage->getConfig()->getTitle()->prepend(__('Distributions'));
        $this->_dataPersistor->clear('current_distribution');

        return $this->_resultPageFactory->create();
    }
}
