<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Model\Distribution\Adapter;

use ArgentCrusade\Flysystem\Selectel\SelectelAdapterFactory;
use ArgentCrusade\Selectel\CloudStorage\Api\ApiClientFactory;
use ArgentCrusade\Selectel\CloudStorage\CloudStorageFactory;
use League\Flysystem\FilesystemFactory;

/**
 * Class Selectel
 */
class Selectel extends BaseAdapter
{
    /**
     * @var ApiClientFactory
     */
    protected $_apiClientFactory;

    /**
     * @var FilesystemFactory
     */
    protected $_filesystemFactory;

    /**
     * @var CloudStorageFactory
     */
    protected $_cloudStorageFactory;

    /**
     * @var SelectelAdapterFactory
     */
    protected $_selectelAdapterFactory;

    /**
     * @param ApiClientFactory       $apiClientFactory
     * @param FilesystemFactory      $filesystemFactory
     * @param CloudStorageFactory    $cloudStorageFactory
     * @param SelectelAdapterFactory $selectelAdapterFactory
     *
     * @inheritdoc
     */
    public function __construct(
        ApiClientFactory $apiClientFactory,
        FilesystemFactory $filesystemFactory,
        CloudStorageFactory $cloudStorageFactory,
        SelectelAdapterFactory $selectelAdapterFactory,
        array $data = []
    ) {
        parent::__construct($data);
        $this->_apiClientFactory       = $apiClientFactory;
        $this->_filesystemFactory      = $filesystemFactory;
        $this->_cloudStorageFactory    = $cloudStorageFactory;
        $this->_selectelAdapterFactory = $selectelAdapterFactory;
    }

    /**
     * @inheritdoc
     */
    public function getFormFields()
    {
        return [
            'field_username'  => [
                'name'   => 'username',
                'config' => [
                    'label'       => __('Username'),
                    'value'       => '',
                    'formElement' => 'input',
                    'validation'  => [
                        'required-entry' => true,
                    ],
                ],
            ],
            'field_password'  => [
                'name'   => 'password',
                'config' => [
                    'label'       => __('Password'),
                    'value'       => '',
                    'formElement' => 'input',
                    'validation'  => [
                        'required-entry' => true,
                    ],
                ],
            ],
            'field_container' => [
                'name'   => 'container',
                'config' => [
                    'label'       => __('Container'),
                    'value'       => '',
                    'formElement' => 'input',
                    'validation'  => [
                        'required-entry' => true,
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function createFilesystem(array $options = [])
    {
        $this->ensureRequiredOptions($options);
        $api        = $this->_apiClientFactory->create([
            'username' => $options[ 'username' ],
            'password' => $options[ 'password' ],
        ]);
        $storage    = $this->_cloudStorageFactory->create([
            'api' => $api,
        ]);
        $container  = $storage->getContainer($options[ 'container' ]);
        $adapter    = $this->_selectelAdapterFactory->create([
            'container' => $container,
        ]);
        $filesystem = $this->_filesystemFactory->create([
            'adapter' => $adapter,
        ]);

        return $filesystem;
    }
}
