<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Model\System\Config\Source\Distribution;

use FjodorMaller\Distribution\Api\Data\Distribution\AdapterPoolInterface;
use FjodorMaller\Distribution\Helper\Data;
use Magento\Framework\Option\ArrayInterface;

/**
 * Class Adapter
 */
class Adapter implements ArrayInterface
{
    /**
     * @var array
     */
    protected $_options;

    /**
     * @var AdapterPoolInterface
     */
    protected $_pool;

    /**
     * @param AdapterPoolInterface $typePool
     */
    public function __construct(
        AdapterPoolInterface $typePool
    ) {
        $this->_pool = $typePool;
    }

    /**
     * Returns the options as array.
     *
     * @return array
     */
    public function toArray()
    {
        if (!$this->_options) {
            $this->_options = [];
            foreach ($this->_pool->getAdapters() as $name => $type) {
                $this->_options[ $name ] = $type->getName();
            }
        }

        return $this->_options;
    }

    /**
     * @inheritdoc
     */
    public function toOptionArray()
    {
        return Data::toOptions($this->toArray());
    }
}
