<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Model\System\Config\Source\Distribution;

use FjodorMaller\Distribution\Helper\Data;
use Magento\Framework\Option\ArrayInterface;

/**
 * Class Health
 */
class Health implements ArrayInterface
{
    const DEAD     = 0;

    const BLEEDING = 1;

    const ALIVE    = 2;

    /**
     * Returns the options as array.
     *
     * @return array
     */
    public static function toArray()
    {
        return [
            self::DEAD     => __('Dead'),
            self::BLEEDING => __('Bleeding'),
            self::ALIVE    => __('Alive'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function toOptionArray()
    {
        return Data::toOptions(self::toArray());
    }
}
