<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Ui\Component\Listing\Distribution\Column;

use FjodorMaller\Base\Ui\Component\Listing\Column\BaseActions;
use FjodorMaller\Distribution\Api\Data\DistributionInterface;
use FjodorMaller\Base\Model\System\Config\Source\Status;

/**
 * Class Actions
 */
class Actions extends BaseActions
{
    /**
     * @inheritdoc
     */
    public function getItemActions()
    {
        return [
            'enable'  => [
                'label'                  => (string)__('Enable'),
                'path'                   => 'distribution/index/enable',
                static::PARAM_SORT_ORDER => 10,
                static::PARAM_IS_VALID   => function ($item) {
                    return (bool)(isset($item[ DistributionInterface::IS_ACTIVE ]) &&
                        $item[ DistributionInterface::IS_ACTIVE ] == Status::DISABLED);
                },
            ],
            'disable' => [
                'label'                  => (string)__('Disable'),
                'path'                   => 'distribution/index/disable',
                static::PARAM_SORT_ORDER => 20,
                static::PARAM_IS_VALID   => function ($item) {
                    return (bool)(isset($item[ DistributionInterface::IS_ACTIVE ]) &&
                        $item[ DistributionInterface::IS_ACTIVE ] == Status::ENABLED);
                },
            ],
            'edit'    => [
                'label'                  => (string)__('Edit'),
                'path'                   => 'distribution/index/edit',
                static::PARAM_SORT_ORDER => 30,
            ],
            'delete'  => [
                'label'                  => (string)__('Delete'),
                'path'                   => 'distribution/index/delete',
                static::PARAM_SORT_ORDER => 40,
                'confirm'                => [
                    'title'   => (string)__('Delete "${ $.$data.name }"'),
                    'message' => (string)__('Are you sure you want to delete the "${ $.$data.name }" record?'),
                ],
            ],
        ];
    }
}
