<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Ui\Component\Listing\Distribution\Column;

use FjodorMaller\Base\Api\OptionItemInterface;
use FjodorMaller\Distribution\Api\Data\Distribution\AdapterPoolInterface;
use Magento\Framework\View\Element\UiComponentFactory;
use Magento\Framework\View\Element\UiComponent\ContextInterface;
use Magento\Ui\Component\Listing\Columns\Column;

/**
 * Class Adapter
 */
class Adapter extends Column
{
    /**
     * @var AdapterPoolInterface
     */
    protected $_pool;

    /**
     * @param AdapterPoolInterface $pool
     *
     * @inheritdoc
     */
    public function __construct(
        AdapterPoolInterface $pool,
        ContextInterface $context,
        UiComponentFactory $uiComponentFactory,
        array $components = [],
        array $data = []
    ) {
        $this->_pool = $pool;
        parent::__construct($context, $uiComponentFactory, $components, $data);
    }

    /**
     * @inheritdoc
     */
    public function prepare()
    {
        $options = [];
        if ($this->_pool->hasAdapters()) {
            foreach ($this->_pool->getAdapters() as $value => $adapter) {
                /* @var $adapter OptionItemInterface */
                $options[] = [
                    'label' => $adapter->getName(),
                    'value' => $adapter->getCode(),
                ];
            }
        }
        $this->setData('options', $options);
        parent::prepare();
    }
}
