<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Ui\Component\Listing\Distribution\Column;

use FjodorMaller\Base\Ui\Component\Listing\Column\BaseMap;
use FjodorMaller\Distribution\Api\Data\DistributionInterface;
use FjodorMaller\Distribution\Model\System\Config\Source\Distribution\Health as Source;

/**
 * Class Health
 */
class Health extends BaseMap
{
    /**
     * @inheritdoc
     */
    public function getMapTemplate()
    {
        return '<span class="grid-map health-%class"><span>%label</span></span>';
    }

    /**
     * @inheritdoc
     */
    protected function _getMap()
    {
        $result = [];
        $map    = Source::toArray();
        foreach ($map as $value => $label) {
            $result[ $value ] = [
                $label,
                strtolower($label),
            ];
        }

        return $result;
    }

    /**
     * @inheritdoc
     */
    protected function _getParams(array $item)
    {
        $map   = $this->getMap();
        $label = __('Unknown');
        $class = strtolower($label);
        if (array_key_exists($item[ DistributionInterface::HEALTH ], $map)) {
            list($label, $class) = $map[ $item[ DistributionInterface::HEALTH ] ];
        }

        return compact('label', 'class');
    }

    /**
     * @inheritdoc
     */
    public function prepareDataSource(array $dataSource)
    {
        if (isset($dataSource[ 'data' ][ 'items' ])) {
            $items =& $dataSource[ 'data' ][ 'items' ];
            foreach ($items as &$item) {
                $item[ DistributionInterface::HEALTH ] = strtr(
                    $this->getMapTemplate(),
                    $this->getParams($item)
                );
            }
        }

        return $dataSource;
    }
}
