<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Setup;

use FjodorMaller\Base\Model\System\Config\Source\Status;
use FjodorMaller\Distribution\Api\Data\DistributionInterface;
use Magento\Framework\DB\Ddl\Table;
use Magento\Framework\Setup\InstallSchemaInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\SchemaSetupInterface;

/**
 * Class InstallSchema
 */
class InstallSchema implements InstallSchemaInterface
{
    /**
     * @inheritdoc
     */
    public function install(SchemaSetupInterface $setup, ModuleContextInterface $context)
    {
        $installer = $setup;
        $installer->startSetup();
        /**
         * Tables
         */
        $tableDistribution = $installer->getTable('fm_distribution');
        /**
         * Create table 'fm_distribution'
         */
        $table = $installer->getConnection()
                           ->newTable($tableDistribution)
                           ->setComment('Distribution Table')
                           ->addColumn(DistributionInterface::DISTRIBUTION_ID, Table::TYPE_INTEGER, null, [
                               'identity' => true,
                               'unsigned' => true,
                               'nullable' => false,
                               'primary'  => true,
                           ], 'Distribution Id')
                           ->addColumn(DistributionInterface::NAME, Table::TYPE_TEXT, 255, [
                               'nullable' => false,
                           ], 'Name')
                           ->addColumn(DistributionInterface::ADAPTER, Table::TYPE_TEXT, 255, [
                               'nullable' => false,
                           ], 'Adapter')
                           ->addColumn(DistributionInterface::OPTIONS, Table::TYPE_TEXT, null, [], 'Options')
                           ->addColumn(DistributionInterface::IS_ACTIVE, Table::TYPE_SMALLINT, null, [
                               'nullable' => false,
                               'default'  => Status::ENABLED,
                           ], 'Is Active')
                           ->addColumn(DistributionInterface::HEALTH, Table::TYPE_SMALLINT, 2, [
                               'nullable' => false,
                               'default'  => Status::ENABLED,
                           ], 'Health')
                           ->addColumn(DistributionInterface::LAST_CHECK, Table::TYPE_DATETIME, null, [
                               'nullable' => true,
                           ], 'Last Check Datetime')
                           ->addColumn(DistributionInterface::LAST_ALIVE, Table::TYPE_DATETIME, null, [
                               'nullable' => true,
                           ], 'Last Alive Datetime');
        $installer->getConnection()->createTable($table);
        $installer->endSetup();
    }
}
