<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Api;

/**
 * Interface DistributionRepositoryInterface
 *
 * @api
 */
interface DistributionRepositoryInterface
{
    /**
     * Save given distribution model.
     *
     * @param \FjodorMaller\Distribution\Api\Data\DistributionInterface $model
     *
     * @return \FjodorMaller\Distribution\Api\Data\DistributionInterface
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function save(Data\DistributionInterface $model);

    /**
     * Retrieves the distribution by id.
     *
     * @api
     *
     * @param int $id
     *
     * @return \FjodorMaller\Distribution\Api\Data\DistributionInterface
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function getById($id);

    /**
     * Get list of distributions by criteria.
     *
     * @param \Magento\Framework\Api\SearchCriteriaInterface $searchCriteria
     *
     * @return \FjodorMaller\Distribution\Api\Data\DistributionSearchResultsInterface
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function getList(\Magento\Framework\Api\SearchCriteriaInterface $searchCriteria);

    /**
     * Delete distribution by model.
     *
     * @param \FjodorMaller\Distribution\Api\Data\DistributionInterface $model
     *
     * @return bool
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function delete(Data\DistributionInterface $model);

    /**
     * Delete distribution by id.
     *
     * @param int $id
     *
     * @return bool
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function deleteById($id);
}
