<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Api;

use League\Flysystem\FilesystemInterface;

interface DistributionServiceInterface
{
    /**
     * @param int $distributionId
     *
     * @return null|FilesystemInterface
     */
    public function getFilesystemByDistributionId($distributionId);

    /**
     * Returns true if distribution with given id is valid.
     *
     * @param int $distributionId
     *
     * @return bool
     */
    public function isValidDistribution($distributionId);

    /**
     * Returns true if given adapter with options is valid.
     *
     * @param string $adapter
     * @param array  $options
     *
     * @return bool
     */
    public function isValidAdapter($adapter, array $options);
}
