<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Distribution\Api\Data\Distribution;

use League\Flysystem\FilesystemInterface;
use FjodorMaller\Base\Api\OptionItemInterface;

interface OptionAdapterInterface extends OptionItemInterface
{
    /**
     * @inheritdoc
     */
    public function getFormFields();

    /**
     * Returns the corresponding filesystem with given options.
     *
     * @param array $options
     *
     * @return FilesystemInterface
     * @throws \InvalidArgumentException
     */
    public function createFilesystem(array $options = []);
}
